#!/bin/bash

die(){
	echo $@
	exit 1
}

[ $EUID -ne 0 ] && {
	sudo $0 $@
	exit $?
}
[ $# -ne 1 ] && die "USAGE: bright <percentage>"
[ $1 -gt 0 ] && [ $1  -le 100 ] || die "Percentage must be an integer between 1 and 100 (inclusive)."

brightness_directory=""
[ -f /sys/class/backlight/intel_backlight/max_brightness ] && {
	brightness_directory="/sys/class/backlight/intel_backlight"
} || [ -f /sys/class/backlight/acpi_video0/max_brightness ] && {
	brightness_directory="/sys/class/backlight/acpi_video0"
} || die "Can't determine backlight controller"


max_brightness="`cat $brightness_directory/max_brightness`"
brightness=$(expr 100 / $1)
brightness=$(expr $max_brightness / $brightness)
echo $brightness > $brightness_directory/brightness
